### ISSUE TITLE
enhancement Fabric Port?

### ISSUE THREAD

**Issue by RotokEralil** [Lothrazar/EnchantingRunes#1]
Hello! Would you consider allowing a fabric port, or doing one?
Amazing mod! (really like the idea)
Minecraft Version: 1.18.1

Forge Version: 

Mod Version: 

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
i have so many forge mods to suppport and more that i want to make, that i dont have time. but its open source if people want to port in a pull request or a fork they are welcome to <3
